
env:
  contexts:
  - name: Default Context
    urls:
    - https://dazzling-puppy-900bdb.netlify.app//
    includePaths:
    - https://dazzling-puppy-900bdb.netlify.app//.*

jobs:
- type: spider
  parameters:
    maxDuration: 5

- type: spiderAjax
  parameters:
    browserId: chrome-headless
    maxDuration: 5

- type: passiveScan-wait
  parameters:
    maxDuration: 5

- type: activeScan

- type: report
  parameters:
    template: traditional-json
    reportDir: C:/Users/Vishnu/Desktop/AI_Product_Lab/01_Active_Products/Nexora.ai/BuildShield 360/zap_scanner
    reportFile: zap_report.json

- type: report
  parameters:
    template: traditional-html
    reportDir: C:/Users/Vishnu/Desktop/AI_Product_Lab/01_Active_Products/Nexora.ai/BuildShield 360/zap_scanner
    reportFile: zap_report.html
